Milestone 2: Update and query animals table
dewslyse/mv-vet-clinic pull request #2
Opened 2022-05-31 21:59 UTC by dewslyse

In this PR, I: 

- 🐇 added a new column (`species`) to the animals table
- 🐦 inserted additional animals' data into table
- 🐎 used database transactions to update and delete records
- 🐒 answered analytical questions using aggregate functions and `GROUP BY`

2022-05-31 23:26 UTC, uwadonat requested changes
Hi **[dewslyse](https://github.com/dewslyse),** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Your commit and pull request messages are very descriptive ✔️
- Your code is well organized ✔️

## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 23:26 UTC, uwadonat commented on queries.sql
> +ROLLBACK;
- [ ] Let's verify that change was made and rollbacked.
`Begin`
  update...

  Select....// to verify if change was made
`ROLLBACK`;
  Select...// to verify that change was undone

2022-05-31 23:26 UTC, uwadonat commented on queries.sql
> +
- [ ] Let's verify that change persists after commit

2022-05-31 23:26 UTC, uwadonat commented on queries.sql
> +WHERE name NOT LIKE '%mon';
- [ ] At this query you should update where species `IS NULL`

2022-05-31 23:26 UTC, uwadonat commented on queries.sql
> +WHERE escape_attempts = 0;
- [ ] Let's add query to delete all records in the animal table and roll back the transaction

2022-06-01 00:13 UTC, uche-inyama approved these changes
Hi <STUDENT_MENTION>, 

Your project is complete!  Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 00:17 UTC, merged